application/common_app/views.py
from flask import Blueprint, render_template,flash,jsonify,request,redirect,url_for
import json
common_app = Blueprint("common_app", __name__, template_folder="./templates", static_folder="./static")

@common_app.route("/")
def index():
    return render_template("index.html")

@common_app.route("/enter_test")
def enter_test():
    return render_template("testscript.html")

@common_app.route("/test",methods=["POST"])
def test():
    where_query = "WHERE"
    posted_data = dict(request.form)
    for key in posted_data.keys():
        for value in request.form.getlist(key):
            where_query += f" {key} = {value} OR"
        where_query = where_query[:-3] + " AND"
    where_query = where_query[:-3]
    print(where_query)
        
    # print(request.form.getlist("test"))
    # data = dict(request.form)
    # print(data)
    # for key, value in request.form.items():
    #     print(key, value)
    print("sendpage")
    return redirect(url_for("common_app.index"))#jsonify({"body":request.json})

application/common_app/templates/common_app/index.html
{% extends "layout.html" %} {% block body %}
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('company_app.login') }}">企業様ログイン</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{{ url_for('applicant_app.index') }}">応募者様のページ</a>
</li>
{% endblock %}

application/common_app/templates/common_app/layout.html
<!DOCTYPE html>
    <title>Test-Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css"rel="stylesheet"type="text/css">
    <link rel="stylesheethref" href="{{url_for('static',filename='style.css')}}">

   <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class ="navbar-brand" href="">Test-Web</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Nav" aria-controls="navbar-Nav" ariae-xpanded="false" aria-label="Toggle-navigation">
                <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"id="navbarNav">
                    <ul class="nav navbar-nav navbar-right">
                        {% if session.company_id %}
                        <li class="navitem　card"><a class="navlink" href="{{url_for('company_app.logout)}}">ログアウト</a></li>
                        <li class="navitem card"><a class="navlink" href="{{url_for('applicant.narrow_down)}}">他社の求人情報はこちら</a></li>
                        {% else %}
                        <li class="navitem "><a class="navlink" href="{{url_for('company_app.login)}}'">企業様はこちら</a></li>
                        <li class="navitem"><a class="navlink" href="{{url_for('applicant.narrow_down)}}">求人情報はこちら</a></li>
                        {% endif %}
                    </ul>
                </div>
        </nav>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
        {{ message }}
        </div>
        {% endfor %}
        <div class="blog-body">
            {% block body %}{% endblock %}
        </div>
    </div>

application/common_app/templates/index.html
{% extends "layout.html" %} {% block body %}
    <a class="nav-link" href="{{ url_for('company_app.login') }}">企業様ログイン</a>
    <a class="nav-link" href="{{ url_for('applicant_app.index') }}">応募者様のページ</a>
    <a class="nav-link" href="{{ url_for('common_app.enter_test') }}">test</a>

{% endblock %}

application/common_app/templates/layout.html
<!DOCTYPE html>
    <title>Test-Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css"rel="stylesheet"type="text/css">
    <link rel="stylesheethref" href="{{url_for('static',filename='style.css')}}">

   <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class ="navbar-brand" href="{{url_for('common_app.index')}}">Test-Web</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Nav" aria-controls="navbar-Nav" ariae-xpanded="false" aria-label="Toggle-navigation">
                <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"id="navbarNav">
                    <ul class="nav navbar-nav navbar-right">
                        {% if session.company_id %}
                        <li class="navitem card" ><a class="navlink" href="{{url_for('company_app.logout')}}">ログアウト</a></li>
                        <li class="navitem card"><a class="navlink" href="{{url_for('applicant_app.narrow_down')}}">他社の求人情報はこちら</a></li>
                        {% else %}
                        <li class="navitem card"><a class="navlink" href="{{url_for('company_app.login')}}">企業様はこちら</a></li>
                        <li class="navitem card"><a class="navlink" href="{{url_for('applicant_app.narrow_down')}}">求人情報はこちら</a></li>
                        {% endif %}
                    </ul>
                </div>
        </nav>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
        {{ message }}
        </div>
        {% endfor %}
        <div class="blog-body">
            {% block body %}{% endblock %}
        </div>
    </div>

application/common_app/templates/testscript.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{{url_for('common_app.test')}}" method="post">
        <input type="text" value=test1 name="test">
        <input type="text" value=test2 name="test">
        <input type="text" value=test3 name="test">
        <input type="text" value=test4 name="test">
        <input type="text" value=udo1 name="udo">
        <input type="text" value=udo2 name="udo">
        <input type="text" value=udo3 name="udo">
        <input type="text" value=udo4 name="udo">
        <input type="submit" value="send">
        <!-- <input type="button" value="send"> -->
    </form>
    <script>
        clickfunction1 = function(){
            var formNumber = 7;
            var previousName = document.forms[0][0].name;
            var valueArray = [];
            var objectList = [];
            for (index = 0; index <= formNumber; index += 1){
                var name = document.forms[0][index].name;
                var value = document.forms[0][index].value;

                if(name == previousName){
                    valueArray.push(value);
                }else{
                    var object = { [previousName] : valueArray }
                    objectList.push(object);
                    previousName = name;
                    valueArray = [];
                    valueArray.push(value);
                };
            }
            object = { [name] : valueArray };
            objectList.push(object);
            const jsonText = JSON.stringify(objectList);

            const url = "{{url_for('common_app.test')}}";
            postData(url, objectList);
        };

        async function postData(url, object){
            const response = await fetch(url,{
                method:"POST",
                mode:"cors",
                headers:{
                    "Content-Type":"application/json"
                },
                body:JSON.stringify(object)
            })
            for (i=0; i<1000000000; i++){

            }
            location.href = "{{url_for('common_app.test')}}";
            // return response.json();
        }
     </script>
</body>
</html>