application/company_app/views.py
from flask import Blueprint, render_template, request, redirect, jsonify, url_for, flash, session
from QueryFunctions import TableOperationBySQL
from config import Config
from Salt import salt
import hashlib
import random
from add_quote import add_single_quote
from datetime import timedelta
from functools import wraps

company_app = Blueprint("company_app", __name__, template_folder="templates", static_folder="./statics")
certifications_table = "companies_certifications"
conditions_table = "companies_conditions_test"

def login_required(company_app):
    @wraps(company_app)
    def inner(*args, **kwargs):
        if session.get("company_id") is None:
            return redirect(url_for("company_app.login"))
        return company_app(*args, **kwargs)
    return inner

@company_app.route("/login",methods=["GET","POST"])
def login():
    error = None
    if session.get("company_id") is not None:
        return redirect(url_for("company_app.enter_company_top"))
    if request.method == "POST":
        table_operater = TableOperationBySQL(Config=Config, table_name=certifications_table)
        company_name = add_single_quote(request.form["company_name"])
        origin_password = request.form["company_password"] + salt
        hash_password = add_single_quote(hashlib.sha256((origin_password).encode('utf-8')).hexdigest())
        company_id = int(request.form["company_id"])
        select_datas = ["company_id","company_name","company_password"]
        condition_dict = {"company_id":company_id,
                        "company_name":company_name,
                        "company_password":hash_password}
        result = table_operater.select(select_datas, condition_dict)
        if result:
            session.permanent = True
            session["company_id"] = company_id
            print("success" ,session.get("company_id"))
            return redirect(url_for("company_app.enter_company_top"))
        else:
            flash("登録情報と一致しません")
            print("登録情報と一致しません")
    return render_template("company_app/login.html")

@company_app.route("/logout")
def logout():
    session.pop('company_id', None)
    print("logout")
    flash("ログアウトしました")
    return redirect(url_for("common_app.index"))


@company_app.route("/enter_new_regist")
def enter_new_regist():
    return render_template("company_app/new_regist.html")

@company_app.route("/new_regist",methods=["POST"])
def new_regist():
    if len(request.form["company_password"]) < 8:
        flash("パスワードは8文字以上の英数字でお願いいたします。")
        return redirect(url_for("company_app.enter_new_regist"))
    origin_password = request.form["company_password"] + salt
    hash_password = add_single_quote(hashlib.sha256((origin_password).encode('utf-8')).hexdigest())
    company_name = add_single_quote(request.form["company_name"])
    ###Generate company_id range(100000000~199999999)
    company_id = random.randint(100000000, 199999999)
    table_operater = TableOperationBySQL(Config=Config, table_name=certifications_table)
    ###Confirm what company_id is only one
    ###
    condition_dict = {"company_id":company_id,
                      "company_name":company_name,
                      "company_password":hash_password}
    
    table_operater.insert(condition_dict)
    flash('新規登録ありがとうございます')
    return render_template("company_app/confirm_id.html",company_id=company_id)

@company_app.route("/enter_company_top")
@login_required
def enter_company_top():
    table_operater = TableOperationBySQL(Config=Config, table_name=conditions_table)
    select_datas = "*"
    condition_dict = {"company_id":session.get("company_id")}
    result = table_operater.select(select_datas, condition_dict)
    if result == ():
        flash("データがありません。データを登録してください")
        return redirect(url_for("company_app.regist_new_conditions"))
    return render_template("company_app/company_top.html",result=next(iter(result)),company_id=session.get("company_id"))

@company_app.route("/regist_new_conditions",methods=["GET","POST"])
@login_required
def regist_new_conditions():
    if request.method == "POST":
        company_id = session.get("company_id")
        company_name = add_single_quote(request.form["company_name"])
        company_message = add_single_quote(request.form["company_message"])
        working_time = add_single_quote(request.form["working_time"])
        table_operater = TableOperationBySQL(Config=Config, table_name=conditions_table)
        condition_dict = {"company_id":company_id,
                        "company_name":company_name,
                        "company_message":company_message,
                        "working_time":working_time}
        table_operater.insert(condition_dict)
        print("insert is succsess")
        return redirect(url_for("company_app.enter_company_top"))
    else:
        return render_template("company_app/regist_new_conditions.html")

@company_app.route("/edit",methods=["POST"])
@login_required
def edit():
    company_id = session.get("company_id")
    company_name = add_single_quote(request.form["company_name"])
    company_message = add_single_quote(request.form["company_message"])
    working_time = add_single_quote(request.form["working_time"])
    where_data = {"company_id":company_id}
    update_data = {"company_name":company_name,
                    "company_message":company_message,
                    "working_time":working_time}
    table_operater = TableOperationBySQL(Config=Config, table_name=conditions_table)
    table_operater.update(where_data, update_data)
    flash("内容を変更いたしました")
    return redirect(url_for("company_app.enter_company_top"))


@company_app.route("/delete",methods=["POST"])
@login_required
def delete():
    table_operater = TableOperationBySQL(Config=Config, table_name=conditions_table)
    identificate_data = {"company_id": int(session.get("company_id"))}
    table_operater.delete(identificate_data)
    flash("内容を破棄しました。")
    return redirect(url_for("company_app.enter_company_top"))

@company_app.app_errorhandler(404)
def non_existant_route(error):
    flash("お探しのページはありません")
    return redirect(url_for('company_app.enter_company_top'))

application/company_app/templates/company_app/company_top.html
{% extends "layout.html" %} {% block body %}
<form action="{{ url_for('company_app.edit') }}" method=post>
    <div class="form-group">
        <p>下記が<b>{{ result.company_name }}</b>様の掲載情報になっています。</p>
        <p>編集を行いたい場合は各項目を編集後、下の編集ボタンを押して編集を完了してください。</p>
    </div>
    <div id="company_name" class="form-group">
        <h3><label for="InputTitle">企業名</label></h3>
        <input type="text" class="form-control" id="InputTitle" value="{{ result.company_name }}" name="company_name">
    </div>
    <div id="company_message" class="form-group">
        <h3><label for="InputTitle">企業からのメッセージ</label></h3>
        <p><textarea name="company_message" cols="100" rows="10">{{ result.company_message }}</textarea></p>
    </div>
    <br>
    <div id="working_time" class="form-group">
        <h3><label for="InputTitle">勤務時間</label></h3>
        <input type="text" class="form-control" id="InputTitle" name="working_time" value="{{ result.working_time }}">
    </div>
    <button type="submit" class="btn btn-primary">編集する</button>
</form>
<br>
<form action="{{ url_for('company_app.delete') }}" method=post>
    <div class="form-group">
        <button type="submit" class="btn btn-primary" value="#">内容を全て削除する</button>
    </div>

{% endblock %}

application/company_app/templates/company_app/confirm_id.html
{% extends "layout.html" %} {% block body %}
<p>新規ご登録ありがとうございました。</p>
<p>下記のIDはログイン時に必要になりますのでお控えください</p>
<p>{{company_id}}</p>
<a class="nav-link" href="{{ url_for('company_app.login') }}">ログインする</a>

{% endblock %}

application/company_app/templates/company_app/layout.html
<!DOCTYPE html>
    <title>Test-Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css"rel="stylesheet"type="text/css">
    <link rel="stylesheethref" href="{{url_for('static',filename='style.css')}}">

   <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class ="navbar-brand" href="">Test-Web</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-Nav" aria-controls="navbar-Nav" ariae-xpanded="false" aria-label="Toggle-navigation">
                <span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"id="navbarNav">
                    <ul class="nav navbar-nav navbar-right">
                        {% if session.company_id %}
                        <li class="navitem"><a class="navlink" href="{{url_for('company_app.logout)}}'">ログアウト</a></li>
                        <li class="navitem"><a class="navlink" href="{{url_for('applicant.narrow_down)}}">他社の求人情報はこちら</a></li>
                        {% else %}
                        <li class="navitem"><a class="navlink" href="{{url_for('company_app.login)}}'">企業様はこちら</a></li>
                        <li class="navitem"><a class="navlink" href="{{url_for('applicant.narrow_down)}}">求人情報はこちら</a></li>
                        {% endif %}
                    </ul>
                </div>
        </nav>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
        {{ message }}
        </div>
        {% endfor %}
        <div class="blog-body">
            {% block body %}{% endblock %}
        </div>
    </div>

application/company_app/templates/company_app/login.html
{% extends "layout.html" %} {% block body %}
<form action="{{ url_for('company_app.login') }}" method=post>
    <div class="form-group">

        <label for="InputTitle">企業様ID</label>
        <input type="text" class="form-control" id="InputTitle" name="company_id">
        </div>
        <div class="form-group">
        <label for="InputTitle">企業様名</label>
        <input type="text" class="form-control" id="InputTitle" name="company_name">
        </div>
    
        <div class="form-group">
        <label for="InputPassword">パスワード</label>
        <input type="password" class="form-control" id="InputPassword" name="company_password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">ログイン</button>
        </form>

    <a class="nav-link" href="{{ url_for('company_app.enter_new_regist') }}">新規ご登録はこちら</a>

{% endblock %}

application/company_app/templates/company_app/new_regist.html
{% extends "layout.html" %} {% block body %}
<form action="{{ url_for('company_app.new_regist') }}" method=post>

        <p>下記の項目をご登録してください</p>
        <div class="form-group"></div>
        <label for="InputTitle">企業様名</label>
        <input type="text" class="form-control" id="InputTitle" name="company_name">
        </div>
    
        <div class="form-group">
        <label for="InputPassword">パスワード</label>
        <input type="password" class="form-control" id="InputPassword" name="company_password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">登録</button>
        </form>
        {% endblock %}

application/company_app/templates/company_app/regist_new_conditions.html
{% extends "layout.html" %} {% block body %}
<p>下記データを入力して新規登録ボタンを押してください</p>
<form action="{{ url_for('company_app.regist_new_conditions') }}" method=post>
    <div class="form-group">

        <label for="InputTitle">企業名</label>
        <input type="text" class="form-control" id="InputTitle" name="company_name">
        </div>
        <div class="form-group">
        <label for="InputTitle">メッセージ</label>
        <p><textarea name="company_message" cols="100" rows="10"></textarea></p>
        </div>
    
        <div class="form-group">
        <label for="InputPassword">勤務時間</label>
        <input type="text" class="form-control" id="InputTitle" name="working_time">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">新規登録</button>
        </form>

{% endblock %}